### ISSUE TITLE
Shovels

### ISSUE THREAD

**Issue by Bareyethir** [Uraneptus/LetMoreLove#2]
Strangely for some reason while having this mod active the functionality of shovels seems to go away and the blocks that you'd normally be able to gather with them cease to register them correctly. Is there a mod that this possibly has conflicts with or something within the mod itself that might be causing the issue?

**Comment by NotTohm** [comment]
Happened to me too, it looks like letmorefishlove:lanternfish_roe_block is messing with the shovel tags

**Comment by Uraneptus** [comment]
It's a know bug, probably caused by a tag. I'm planning on fixing this, but I'm on vacation rn
